In [1]:
import pandas as pd
import os
import numpy as np

## Import Data

In [2]:
processed_data_path = os.path.join(os.path.pardir, 'data', 'processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [3]:
train_df = pd.read_csv(train_file_path, index_col = 'PassengerId')
test_df = pd.read_csv(test_file_path, index_col = 'PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Survived            891 non-null    int64  
 1   Age                 891 non-null    float64
 2   Fare                891 non-null    float64
 3   FamilySize          891 non-null    int64  
 4   IsMother            891 non-null    int64  
 5   IsMale              891 non-null    int64  
 6   Deck_A              891 non-null    int64  
 7   Deck_B              891 non-null    int64  
 8   Deck_C              891 non-null    int64  
 9   Deck_D              891 non-null    int64  
 10  Deck_E              891 non-null    int64  
 11  Deck_F              891 non-null    int64  
 12  Deck_G              891 non-null    int64  
 13  Deck_Z              891 non-null    int64  
 14  Pclass_1            891 non-null    int64  
 15  Pclass_2            891 non-null    int64  
 16  Pclass_3

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 418 non-null    float64
 1   Fare                418 non-null    float64
 2   FamilySize          418 non-null    int64  
 3   IsMother            418 non-null    int64  
 4   IsMale              418 non-null    int64  
 5   Deck_A              418 non-null    int64  
 6   Deck_B              418 non-null    int64  
 7   Deck_C              418 non-null    int64  
 8   Deck_D              418 non-null    int64  
 9   Deck_E              418 non-null    int64  
 10  Deck_F              418 non-null    int64  
 11  Deck_G              418 non-null    int64  
 12  Deck_Z              418 non-null    int64  
 13  Pclass_1            418 non-null    int64  
 14  Pclass_2            418 non-null    int64  
 15  Pclass_3            418 non-null    int64  
 16  Title

## Data preparation

In [6]:
#create input and output. Of train_df
#X = train_df.loc[:,'Age':].as_matrix().astype('float') #take all input columns and rows

##as_matrix is deprecated, so I use to_numpy instead: https://stackoverflow.com/questions/60164560/attributeerror-series-object-has-no-attribute-as-matrix-why-is-it-error
###to_numpy is actually the same as df.values: https://pandas.pydata.org/pandas-docs/version/1.0.1/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values

X = train_df.loc[:,'Age':].to_numpy().astype('float') #take all input columns and rows
y = train_df['Survived'].ravel() #output column is Survived.Ravel creates'flat, one-dimensional array'

In [7]:
print(X.shape, y.shape)  ##upper case for matrix, lower case for one-dimensional (i.e. vector)

(891, 32) (891,)


In [8]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X,y,test_size = 0.2, random_state = 0)
print(X_train.shape, y_train.shape)
print(X_test.shape,y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [9]:
##average survival in train and test
print('mean survival train: {0:.3f}'.format(np.mean(y_train)))
print('mean survival test: {0:.3f}'.format(np.mean(y_test)))

mean survival train: 0.383
mean survival test: 0.385


### Check Scikit-Learn

In [10]:
import sklearn

In [11]:
sklearn.__version__

'0.23.1'

## Baseline Model

In [12]:
#import function
from sklearn.dummy import DummyClassifier

In [13]:
#create model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0) ## we want to give each unknown value that of the most frequent, i.e. not survived for the base line model

In [14]:
#train model
model_dummy.fit(X_train,y_train)  ##fit(input, output)

DummyClassifier(random_state=0, strategy='most_frequent')

In [15]:
print('score for baseline model: {0:.2f}'.format(model_dummy.score(X_test,y_test))) ##this is the Accuracy test.

score for baseline model: 0.61


In [16]:
#performance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [17]:
#accuracy score
print('accuracy for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

accuracy for baseline model: 0.61


In [18]:
#confusion_matrix
print('accuracy for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))

accuracy for baseline model: 
 [[110   0]
 [ 69   0]]


In [19]:
#precision and recall
print('accuracy for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('accuracy for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

accuracy for baseline model: 0.00
accuracy for baseline model: 0.00


c:\users\pitsc\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## First Kaggle Submission

In [20]:
#converting to the matrix
test_X = test_df.to_numpy().astype('float')

In [21]:
#get predictions
predictions = model_dummy.predict(test_X)

In [22]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})

In [23]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [24]:
#save dataframe to file
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [25]:
df_submission.to_csv(submission_file_path, index=False)

In [26]:
def get_submission_file(model, filename):
    #convertion to matrix
    test_X = test_df.to_numpy().astype('float')
    #make predictions
    predictions = model.predict(test_X)
    #make submission df
    df_submission = pd.DataFrame({'PassengerId':test_df.index, 'Survived': predictions})
    #submission file
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)
    #write to file
    df_submission.to_csv(submission_file_path, index=False)

In [27]:
#get submission file
get_submission_file(model_dummy, '01_dummy.csv')

## Logistic Regression Model

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
#create model
model_logr_1 = LogisticRegression(random_state = 0, solver ='liblinear')

In [30]:
#train model
model_logr_1.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [31]:
print(model_logr_1.score(X_test, y_test))

0.8324022346368715


In [32]:
#performance metrics
#accuracy score
print('accuracy for logistic regression: {0:.2f}'.format(accuracy_score(y_test, model_logr_1.predict(X_test))))
#confusion_matrix
print('confusion matrix for logistic regression: \n {0}'.format(confusion_matrix(y_test, model_logr_1.predict(X_test))))
#precision and recall
print('precision for baseline model: {0:.2f}'.format(precision_score(y_test, model_logr_1.predict(X_test))))
print('recall for baseline model: {0:.2f}'.format(recall_score(y_test, model_logr_1.predict(X_test))))

accuracy for logistic regression: 0.83
confusion matrix for logistic regression: 
 [[95 15]
 [15 54]]
precision for baseline model: 0.78
recall for baseline model: 0.78


In [33]:
#model coefficients
model_logr_1.coef_

array([[-0.03284571,  0.00421868, -0.52750517,  0.6337093 , -1.11100699,
        -0.01381988, -0.30260418, -0.5336007 ,  0.40470193,  0.98499702,
         0.28096674, -0.28401557, -0.52261791,  0.59187681,  0.13636844,
        -0.71423779,  0.23483037,  1.09824746,  0.15369976, -1.55923361,
         0.73648432, -0.15482545, -0.49519539, -0.11830595, -0.03719404,
         0.00742179,  0.16208566,  0.12450843,  0.11944784, -0.22994881,
        -0.17585244,  0.1898599 ]])

### Second Kaggle Submission

In [34]:
#get submisson file
get_submission_file(model_logr_1, '02_lr.csv')

## Hyperparamter Optimization

In [47]:
model_lr = LogisticRegression(random_state = 0, solver ='liblinear')

In [43]:
from sklearn.model_selection import GridSearchCV

In [48]:
##make grid for crossvalidation
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3) ##cv is k-fold

In [49]:
##pass the training data to the assortment of different models we created in the grid clf
clf.fit(X_train, y_train)

GridSearchCV(cv=3,
             estimator=LogisticRegression(random_state=0, solver='liblinear'),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [50]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [51]:
print('best score: {0:.2f}'.format(clf.best_score_))

best score: 0.83


In [52]:
print('score for lr: {0:.2f}'.format(clf.score(X_test,y_test)))

score for lr: 0.83


### Making Third Submission

In [53]:
get_submission_file(clf,'03_lr.csv')

## Feature Normalization and Standardization

In [54]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

#### Feature Normalization

In [56]:
#feature normalization
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [57]:
X_train_scaled[:,0].min(), X_train_scaled[:,0].max() ##print min and max to check if normalization worked

(0.0, 1.0)

In [58]:
#Also have to normalize test data, since model will expect normalized data
X_test_scaled = scaler.transform(X_test)

#### Feature Standardization

In [59]:
##basically the same thing
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### Create Model after Norm/Standardization

In [60]:
model_lr = LogisticRegression(random_state = 0, solver ='liblinear')
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3) ##cv is k-fold
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3,
             estimator=LogisticRegression(random_state=0, solver='liblinear'),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [61]:
clf.best_score_

0.8132231795671855

In [62]:
print('score for lr: {0:.2f}'.format(clf.score(X_test_scaled,y_test)))

score for lr: 0.84


## Model Persistence

In [63]:
import pickle

In [64]:
#create the file path
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [65]:
#open files to write
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [66]:
#persist/save the model and scaler
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [67]:
#close the files.
model_file_pickle.close()
scaler_file_pickle.close()

#### load the persisted file

In [70]:
#open files in read mode
model_file_pickle = open(model_file_path, 'rb')
scaler_file_pickle = open(scaler_file_path, 'rb')
#load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
#close files
model_file_pickle.close()
scaler_file_pickle.close()

In [71]:
clf_loaded

GridSearchCV(cv=3,
             estimator=LogisticRegression(random_state=0, solver='liblinear'),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [72]:
scaler_loaded

StandardScaler()

In [73]:
X_test_scaled = scaler_loaded.transform(X_test)
print(clf_loaded.score(X_test_scaled, y_test))

0.8435754189944135
